#!/bin/bash

checkip () {
	ipdata=$(curl -s ipinfo.io/$ip)
    echo $ipdata | jq -r '[.country, .city] | join(" ")'
}

battery="BAT0";

battery_status() {
    
    if [ -d /sys/class/power_supply/$battery ]; then
        
        charge="$(cat /sys/class/power_supply/$battery/capacity)"
        echo "$charge% |"

    fi
}

while true; do
	
    xsetroot -name "$(checkip) | $(battery_status) $( date +"%R" )"

	sleep 10s

done


